export const CRYPTO_DEV_TOKEN_CONTRACT_ADDRESS =
  "0x786BbF78eA8ac29f25bDcF1F33c14A1ffF618C68";

import CRYPTO_DEV_TOKEN_CONTRACT_ABI_INTERFACE from "../contracts/CryptoDevsToken.json";
export const CRYPTO_DEV_TOKEN_CONTRACT_ABI =
  CRYPTO_DEV_TOKEN_CONTRACT_ABI_INTERFACE.abi;

import EXCHANGE_CONTRACT_INTERFACE from "../contracts/Exchange.json";
export const EXCHANGE_CONTRACT_ABI = EXCHANGE_CONTRACT_INTERFACE.abi;

import EXCHANGE_CONTRACT from "../contracts/Exchange-address.json";
export const EXCHANGE_CONTRACT_ADDRESS = EXCHANGE_CONTRACT.contractAddress;
